Use of cursor
I get the following error at iteration 1475 (36875 items retrieved):

Error: 400, {"service-error":{"status":{"statusCode":"INVALID_INPUT","statusText":"Invalid Input (cursor)"}}}

The reason might be that the cursor value has a "+" in it: AoJX+YJNMjItczIuMC04NTA3Nzc5MDY5MQ==

However, all cursus the worked had a "/" in it:

AoJR/oJNMjItczIuMC04NTA2OTk4ODc2Mw==

I'm not sure how to solve this yet.